CC          ?= gcc
AR          ?= ar
FMT         ?= clang-format
INSTALL     := install

INSTALL_DIR ?= /usr/local
MAN_DIR     ?= /usr/share/man/man3

LIBNAME     := libutil
MANPAGE     := $(LIBNAME).3
